name: Publish npm package
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master

jobs:
  pre-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        id: version_bump
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: 'master'
          DEFAULT_BUMP: 'patch'
          WITH_V: true

  publish:
    runs-on: ubuntu-latest
    needs: pre-publish
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@stradivarit'

      - name: Get new tag
        id: get_version
        run: echo ::set-output name=VERSION::$( git describe --tag --abbrev=0 )
      - run: git describe --tag --abbrev=0
      - run: npm --no-git-tag-version version $( git describe --tag --abbrev=0 )

      - run: npm ci
      - run: npm run build

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
